trigger:
  - "*"

variables:
  python.version: '2.7'

pool:
  name: 'Default'
  demands:
    - agent.os -equals Linux


strategy:
  matrix:
    ubuntu14:
      containerImage: ubuntu:14.04
    ubuntu16:
      containerImage: ubuntu:16.04
    ubuntu18:
      containerImage: ubuntu:18.04

container: $[ variables['containerImage'] ]

steps:
  - bash: |
      set -eux

      pwd
      whoami
      env
      sleep 20
