trigger:
  - "*"

pool:
  name: 'Default'
  demands:
    - agent.os -equals Linux

container:
  image: "localhost:5000/test/sentry-test:latest"

variables:
  NODE_ENV: development
  PIP_DISABLE_PIP_VERSION_CHECK: on
  PIP_QUIET: 1
  SENTRY_LIGHT_BUILD: 1
  SENTRY_SKIP_BACKEND_VALIDATION: 1
  SOUTH_TESTS_MIGRATE: 0
  DJANGO_VERSION: ">=1.8,<1.9"
  # node's version is pinned by .nvmrc and is autodetected by `nvm install`.
  NODE_DIR: "${HOME}/.nvm/versions/node/v$(< .nvmrc)"
  YARN_VERSION: "1.13.0"
  NODE_OPTIONS: --max-old-space-size=4096

services:
  memcached: "memcached:1.4.36-alpine"
  postgresql: "postgres:9.6.13-alpine"
  redis: "redis:5.0.5-alpine"

steps:
  - bash: |
      set -eux
      env
      pwd
      whoami

      # FIXME permissions workaround
      sudo chown -R $(id -u):$(id -g) /usr/local

      # docker run -d --network host --name clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server:18.14.9
      # docker run -d --network host --name snuba --env SNUBA_SETTINGS=test --env CLICKHOUSE_SERVER=localhost:9000 getsentry/snuba
      # docker ps -a
      yarn install --pure-lockfile

      pip install -e ".[dev,tests,optional]"

      make test-acceptance
